### ISSUE TITLE
Support pod-query matching a single word

### ISSUE THREAD

**Issue by vsimon** [stern/stern#158] opened 2021-09-15 20:21 UTC
**What would you like to be added**:

I would like to use the existing pod-query CLI argument to be flexible enough to match existing pod names without resorting to label selectors (both adding the labels and knowing how to select off them). Since the default value is ".*", it seemed like regexes would be supported.

**Why is this needed**:

Consider, a collection of deployments in the same namespace like:

```
app
app-admin
app-sdk
```

To match the "app" pod, I tried

`stern -n <namespace> "app"`, but it matches all 3.

`stern -n <namespace> "app\$"`, but it matches 0.

`stern -n <namespace> "app$"`, but it matches 0.

`stern -n <namespace> "^app$"`, but it matches 0.

`stern -n <namespace> "^app\$"`, but it matches 0.

**Comment by superbrothers** [comment] 2021-09-18 07:23
I was not able to reproduce the problem as it works as expected in my environment.

- `stern "app"`, but it matches all 3.
- `stern "app\$"`, but it matches 1.
- `stern "app$"`, but it matches 1.
- `stern "^app$"`, but it matches 1.
- `stern "^app\$"`, but it matches 1.

I have checked with Zsh and Bash below, and both are works fine.

```
$ zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)

$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I created the environment with the following steps:

```
$ stern --version
version: 1.20.1
commit: a384d35f36e43953ac3c6af5a20ffc97cb8205cf
built at: 2021-09-11T12:17:12Z

$ kind create cluster --image=kindest/node:v1.22.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-25T19:54:13Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl run app --image nginxinc/nginx-unprivileged
pod/app created
$ kubectl run app-admin --image nginxinc/nginx-unprivileged
pod/app-admin created
$ kubectl run app-sdk --image nginxinc/nginx-unprivileged
pod/app-sdk created

$ kubectl get po
NAME        READY   STATUS    RESTARTS   AGE
app         1/1     Running   0          2m41s
app-admin   1/1     Running   0          2m38s
app-sdk     1/1     Running   0          22s
```

Please provide the version of stern. Also, please create an environment using the steps above and check again if the problem occurs.

**Comment by vsimon** [comment] 2021-09-18 07:53
```
stern --version
version: 1.20.1

zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
```

Thanks, I see your example. I was imagining the example with deployments of replica count 1 instead...

```
app-575b45fdb8-xrkq4         1/1     Running   0          2m41s
app-admin-5b5d499798-j8drh   1/1     Running   0          2m38s
app-sdk-b96cdb967-qw8wn     1/1     Running   0          22s
```

Now I see why `stern "app\$"` didn't match. Is there anyway to match the single "app" pod without having to do "get pods" to discover the exact alphanumeric characters or remember a regex expression taking into account the 10-character alphanumeric part in the middle and 5-character hex part at the end?

Also, I tried this which I would have thought would match the first pod ("app-575b45fdb8-xrkq4") but it matched 0.

``` 
stern  "app-[0-9a-z]{10}-[0-9a-z]{5}"
```

**Comment by superbrothers** [comment] 2021-09-18 08:18
Umm... I still can't reproduce the problem in my environment :thinking: 

```
$ kubectl create deploy app --image nginxinc/nginx-unprivileged
$ kubectl create deploy app-admin --image nginxinc/nginx-unprivileged
$ kubectl create deploy app-sdk --image nginxinc/nginx-unprivileged

$ kubectl get po
NAME                        READY   STATUS              RESTARTS   AGE
app-756d764c46-njkvx        0/1     ContainerCreating   0          12s
app-admin-dc858d4d4-wmbh7   0/1     ContainerCreating   0          9s
app-sdk-55cbbb55-65tz4      0/1     ContainerCreating   0          6s

$ stern "app-[0-9a-z]{10}-[0-9a-z]{5}" | head -n 3
+ app-756d764c46-njkvx › nginx-unprivileged
app-756d764c46-njkvx nginx-unprivileged /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
app-756d764c46-njkvx nginx-unprivileged /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
app-756d764c46-njkvx nginx-unprivileged /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
```

By default, stern will only output logs since 48 hours ago. If logs are not after that time, nothing will be output. Therefore, please check it in the newly created environment using the steps I have provided.

```
$ stern -h | grep -- --since
  -s, --since duration             Return logs newer than a relative duration like 5s, 2m, or 3h. (default 48h0m0s)
```

> Is there a friendly way to match the "app" pod in the Deployment case without having to do "get pods" to discover the exact alphanumeric characters or for beginner types to remember the regex expression taking into account the 10-character alphanumeric part in the middle and 5-character part at the end i.e. stern "app-[0-9a-z]{10}-[0-9a-z]{5}" ?

The easiest way to do this is to use a label selector.

```
$ kubectl get deploy app --show-labels
NAME   READY   UP-TO-DATE   AVAILABLE   AGE    LABELS
app    1/1     1            1           7m7s   app=app

$ stern -l app=app | head -n 3
+ app-756d764c46-njkvx › nginx-unprivileged
app-756d764c46-njkvx nginx-unprivileged /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
app-756d764c46-njkvx nginx-unprivileged /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
app-756d764c46-njkvx nginx-unprivileged /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
```

**Comment by vsimon** [comment] 2021-09-18 19:17
> Umm... I still can't reproduce the problem in my environment

Yes, you can't reproduce because you are now running `stern "app-[0-9a-z]{10}-[0-9a-z]{5}"` command to match the pods instead of just "app$".  Which makes sense, those are the actual app names. 

The default argument takes a "pod-query", can there be an option for a "deployment-query"? 😄  

That way one could pass "app$" and have it match the `app-756d764c46-njkvx` pod without the longer "app-[0-9a-z]{10}-[0-9a-z]{5}" regex.


Agreed, the easiest way to do this is to use a label selector. Just so I can use this tool easier, I have add something extra. Someone will ask: "Why are you adding these labels?" The answer being "Because I want to use stern".

**Comment by superbrothers** [comment] 2021-09-19 00:42
Pods created by Deployment already have several labels, so there is no need to add extra labels. However, it is certainly easier to search by the name of the Deployment.

**Comment by superbrothers** [comment] 2021-09-19 00:47
The issues addressed in this issue have been resolved. Therefore, I'm closing this issue.

The following is a request for a new feature, so please create a new issue.

> Agreed, the easiest way to do this is to use a label selector. Just so I can use this tool easier, I have add something extra. Someone will ask: "Why are you adding these labels?" The answer being "Because I want to use stern in an easier way".

**Closed by superbrothers** 2021-09-19 00:47 UTC
Labels: kind/bug
