### ISSUE TITLE
Disable follow if a flag is supplied

### ISSUE THREAD

**Issue by superbrothers** [stern/stern#27] opened 2020-10-22 02:00 UTC
**Note:** this issue was imported from https://github.com/wercker/stern/issues/105, but it was originally created by [migueleliasweb](https://github.com/migueleliasweb)...

Hey all,

I'm aware the idea of disabling the follow feature was mentioned a while ago in #34 but I don't think it was ever implemented. Just to clarify, I'm not talking about changing the default behaviour.

Is there any workarounds for this?

**Comment by padelt** [comment] 2022-05-13 12:51
Duplicate of #15

**Closed** 2022-06-08 23:52 UTC
